=== DavevanIersel/WinDash/src/widgets/widget-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "description": "Generated from filename"
      },
      "name": {
        "type": "string",
        "description": "A name for the widget"
      },
      "html": {
        "type": "string",
        "description": "The HTML page that should be loaded for a custom widget"
      },
      "url": {
        "type": "string",
        "description": "The URL which should be loaded"
      },
      "x": {
        "type": "number",
        "description": "Horizontal position of the upper left corner of the widget"
      },
      "y": {
        "type": "number",
        "description": "Vertical position of the upper left corner of the widget"
      },
      "width": {
        "type": "number",
        "description": "Width of the widget"
      },
      "height": {
        "type": "number",
        "description": "Height of the widget"
      },
      "touchEnabled": {
        "type": "boolean",
        "description": "Indicates whether touch controls are simulated, especially great in combination with a mobile user agent"
      },
      "enabled": {
        "type": "boolean",
        "description": "Toggle widget on or off"
      },
      "customUserAgent": {
        "type": "object",
        "additionalProperties": {
          "type": "string",
          "description": "A custom user agent for a specific domain"
        },
        "description": "Mapping of domains to custom user agents"
      },
      "permissions": {
        "type": "object",
        "additionalProperties": {
          "type": "boolean",
          "description": "Indicates whether a specific permission is granted"
        },
        "description": "Mapping of permission types (strings) to booleans"
      },
      "customScript": {
        "type": "string",
        "description": "A custom JS script you want to be loaded on the widget webpage"
      },
      "devTools": {
        "type": "boolean",
        "description": "Enable developer tools for this widget"
      }
    },
    "anyOf": [
      {
        "required": ["html"],
        "not": {
          "required": ["url"]
        }
      },
      {
        "required": ["url"],
        "not": {
          "required": ["html"]
        }
      }
    ],
    "required": [
      "name",
      "x",
      "y",
      "width",
      "height",
      "enabled"
    ],
    "additionalProperties": true
  }

=== DavevanIersel/WinDash/src/widgets/buienradar.widget.json
{
  "$schema": "widget-schema.json",
  "name": "Buienradar",
  "url": "https://www.buienradar.nl/",
  "enabled": true,
  "x": 58,
  "y": 4,
  "width": 16,
  "height": 34,
  "touchEnabled": false,
  "customScript": "const pauseButton = document.querySelector('.btn-pause');\n\nif (pauseButton && pauseButton.style.display !== 'none') {\n    pauseButton.click();\n} else {\n    const observer = new MutationObserver(() => {\n        if (pauseButton && pauseButton.style.display !== 'none') {\n            pauseButton.click();\n            observer.disconnect(); // Stop observing once the button is clicked\n        }\n    });\n    observer.observe(document.body, { childList: true, subtree: true });\n}"
}

=== DavevanIersel/WinDash/src/widgets/ms-todo.widget.json
{
  "$schema": "widget-schema.json",
  "name": "Microsoft Todo",
  "url": "https://to-do.live.com/tasks/AQMkADAwATM3ZmYAZS1jYTEzLTY1YjktMDACLTAwCgAuAAADyqr38IduTEGsZZ2vTL9i7QEAwnT1PlmmVkCwuln8igKb4AAHX-siuQAAAA==",
  "enabled": true,
  "x": 2,
  "y": 2,
  "width": 15,
  "height": 8,
  "touchEnabled": false
}

=== DavevanIersel/WinDash/src/widgets/my-anime-list.widget.json
{
  "$schema": "widget-schema.json",
  "name": "MyAnimeList Profile",
  "url": "https://myanimelist.net/animelist/Dn_Dave?status=7",
  "enabled": true,
  "x": 2,
  "y": 11,
  "width": 15,
  "height": 8,
  "customUserAgent": {
    "open.spotify.com": "Mozilla/5.0 (Android 15; Mobile; rv:133.0) Gecko/133.0 Firefox/133.0"
  }
}
